/**
 * Integration Tests: Manual Skills End-to-End
 *
 * Tests that manual skills work correctly through the resources/* endpoints.
 * Validates baseline functionality for manually-written skill content.
 */

import { compileServerFromCode } from '../../src/index.js';

describe('Skill Manual E2E - Manual Skills', () => {
  it('should compile and serve traditional manual skill', async () => {
    const code = `
      import { ISkill, SkillHelper } from 'simply-mcp';

      interface ManualSkill extends ISkill {
        name: 'weather_analysis';
        description: 'Analyze weather patterns';
        skill: string;
      }

      export default class TraditionalServer {
        weatherAnalysis: SkillHelper<ManualSkill> = () => {
          return '# Weather Analysis\\n\\nThis skill analyzes weather patterns.';
        };
      }
    `;

    const { server, parsed } = await compileServerFromCode(code, {
      name: 'traditional',
      version: '1.0.0',
      silent: true,
    });

    // Compilation should work
    expect(parsed.skills).toHaveLength(1);
    expect(parsed.skills[0].name).toBe('weather_analysis');
    expect(parsed.skills[0].isAutoGenerated).toBe(false);

    // Registration should work
    const allResources = await server.listResources();
    const skills = allResources.filter(r => r.uri.startsWith('skill://'));
    expect(skills).toHaveLength(1);
    expect(skills[0].uri).toBe('skill://weather_analysis');
    expect(skills[0].mimeType).toBe('text/markdown');

    // resources/read should return manual content
    const result = await server.readResource('skill://weather_analysis');
    expect(result.contents[0].text).toBe('# Weather Analysis\n\nThis skill analyzes weather patterns.');
  });

  it('should support dynamic manual skills (function-based content)', async () => {
    const code = `
      import { ISkill, SkillHelper } from 'simply-mcp';

      interface DynamicManualSkill extends ISkill {
        name: 'dynamic_help';
        description: 'Dynamic help content';
        skill: string;
      }

      export default class DynamicServer {
        dynamicHelp: SkillHelper<DynamicManualSkill> = () => {
          const timestamp = new Date().toISOString();
          return \`# Help\\n\\nGenerated at: \${timestamp}\`;
        };
      }
    `;

    const { server } = await compileServerFromCode(code, {
      name: 'dynamic',
      version: '1.0.0',
      silent: true,
    });

    const result = await server.readResource('skill://dynamic_help');
    const content = result.contents[0].text;

    expect(content).toContain('# Help');
    expect(content).toContain('Generated at:');
  });

  it('should support hidden manual skills', async () => {
    const code = `
      import { ISkill, SkillHelper } from 'simply-mcp';

      interface HiddenManualSkill extends ISkill {
        name: 'internal_docs';
        description: 'Internal documentation';
        skill: string;
        hidden: true;
      }

      export default class HiddenServer {
        internalDocs: SkillHelper<HiddenManualSkill> = () => '# Internal Docs\\n\\nInternal content.';
      }
    `;

    const { server } = await compileServerFromCode(code, {
      name: 'hidden',
      version: '1.0.0',
      silent: true,
    });

    // Should be hidden from list
    const allResources = await server.listResources();
    const skills = allResources.filter(r => r.uri.startsWith('skill://'));
    expect(skills).toHaveLength(0);

    // But accessible via readResource
    const result = await server.readResource('skill://internal_docs');
    expect(result.contents[0].text).toBe('# Internal Docs\n\nInternal content.');
  });

  it('should maintain all manual skill features from FL-2', async () => {
    const code = `
      import { ISkill, SkillHelper } from 'simply-mcp';

      interface FullFeaturedManualSkill extends ISkill {
        name: 'full_featured';
        description: 'Full featured manual skill';
        skill: string;
        hidden: false;
      }

      export default class FullServer {
        fullFeatured: SkillHelper<FullFeaturedManualSkill> = () => {
          return \`# Full Featured Skill

## Overview
This is a comprehensive manual skill.

## Features
- Custom markdown
- Complete control
- Narrative content

## Usage
Use this skill when you need detailed explanations.
\`;
        };
      }
    `;

    const { server, parsed } = await compileServerFromCode(code, {
      name: 'full',
      version: '1.0.0',
      silent: true,
    });

    // All metadata should be preserved
    expect(parsed.skills[0].name).toBe('full_featured');
    expect(parsed.skills[0].hidden).toBe(false);
    expect(parsed.skills[0].isAutoGenerated).toBe(false);

    const result = await server.readResource('skill://full_featured');
    const content = result.contents[0].text;

    // Manual content should be returned exactly as provided
    expect(content).toContain('# Full Featured Skill');
    expect(content).toContain('## Overview');
    expect(content).toContain('## Features');
    expect(content).toContain('## Usage');
  });

  it('should work in server with only manual skills (no auto-gen)', async () => {
    const code = `
      import { ISkill, SkillHelper } from 'simply-mcp';

      interface Skill1 extends ISkill {
        name: 'skill_one';
        description: 'First skill';
        skill: string;
      }

      interface Skill2 extends ISkill {
        name: 'skill_two';
        description: 'Second skill';
        skill: string;
      }

      export default class ManualOnlyServer {
        skillOne: SkillHelper<Skill1> = () => '# Skill One';
        skillTwo: SkillHelper<Skill2> = () => '# Skill Two';
      }
    `;

    const { server } = await compileServerFromCode(code, {
      name: 'manual-only',
      version: '1.0.0',
      silent: true,
    });

    const allResources = await server.listResources();
    const skills = allResources.filter(r => r.uri.startsWith('skill://'));

    expect(skills).toHaveLength(2);
    expect(skills[0].name).toBe('skill_one');
    expect(skills[1].name).toBe('skill_two');

    const result1 = await server.readResource('skill://skill_one');
    const result2 = await server.readResource('skill://skill_two');

    expect(result1.contents[0].text).toBe('# Skill One');
    expect(result2.contents[0].text).toBe('# Skill Two');
  });

  it('should not break existing server code', async () => {
    // This is a real-world pattern from FL-2 baseline
    const code = `
      import { ISkill, SkillHelper } from 'simply-mcp';

      interface WeatherSkill extends ISkill {
        name: 'weather_forecast';
        description: 'Get weather forecast for a location';
        skill: string;
      }

      export default class WeatherServer {
        weatherForecast: SkillHelper<WeatherSkill> = () => {
          return \`# Weather Forecast Skill

Use this skill to access weather data and forecasts.

## Available Operations
- Current weather conditions
- 7-day forecasts
- Historical data

## Usage Tips
Always specify the location clearly for accurate results.
\`;
        };
      }
    `;

    const { server } = await compileServerFromCode(code, {
      name: 'weather',
      version: '1.0.0',
      silent: true,
    });

    const result = await server.readResource('skill://weather_forecast');
    const content = result.contents[0].text;

    // Should work exactly as before
    expect(content).toContain('# Weather Forecast Skill');
    expect(content).toContain('## Available Operations');
    expect(content).toContain('## Usage Tips');
  });
});
