/**
 * Unit Tests: Empty Skills Rule
 *
 * Tests the validation rule that detects auto-generated skills with
 * empty or missing components.
 */

import { describe, it, expect } from '@jest/globals';
import { checkEmptySkills } from '../../src/server/compiler/validators/rules/empty-skills.js';
import type { ValidationContext } from '../../src/server/compiler/validators/types.js';
import type { ParsedSkill } from '../../src/server/compiler/types.js';

/**
 * Helper to create a minimal validation context for testing
 */
function createTestContext(overrides?: Partial<ValidationContext>): ValidationContext {
  return {
    tools: new Map(),
    resources: new Map(),
    prompts: new Map(),
    skills: new Map<string, ParsedSkill>(),
    sourceFile: '/test/server.ts',
    config: {
      enabled: true,
      rules: {
        orphanedHidden: 'warn',
        invalidReferences: 'error',
        nonHiddenComponents: 'warn',
        emptySkills: 'warn'
      },
      strict: false
    },
    ...overrides
  };
}

describe('Empty Skills Rule', () => {
  describe('Auto-Generated Skills', () => {
    it('should warn about auto-generated skill with no components', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            description: 'An empty skill',
            isAutoGenerated: true
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].rule).toBe('empty-skill-components');
      expect(warnings[0].severity).toBe('warning');
      expect(warnings[0].message).toContain('empty_skill');
      expect(warnings[0].message).toContain('uses auto-generation');
      expect(warnings[0].message).toContain('no components');
      expect(warnings[0].suggestion).toContain('Add component arrays');
      expect(warnings[0].suggestion).toContain('Switch to manual content');
    });

    it('should warn about auto-generated skill with empty arrays', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            description: 'Empty skill',
            isAutoGenerated: true,
            tools: [],
            resources: [],
            prompts: []
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].message).toContain('empty_skill');
    });

    it('should warn about auto-generated skill with undefined component arrays', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            isAutoGenerated: true,
            tools: undefined,
            resources: undefined,
            prompts: undefined
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].message).toContain('empty_skill');
    });

    it('should not warn when auto-generated skill has tools', () => {
      const context = createTestContext({
        skills: new Map([
          ['tool_skill', {
            name: 'tool_skill',
            isAutoGenerated: true,
            tools: ['tool1', 'tool2']
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should not warn when auto-generated skill has resources', () => {
      const context = createTestContext({
        skills: new Map([
          ['resource_skill', {
            name: 'resource_skill',
            isAutoGenerated: true,
            resources: ['file://1', 'file://2']
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should not warn when auto-generated skill has prompts', () => {
      const context = createTestContext({
        skills: new Map([
          ['prompt_skill', {
            name: 'prompt_skill',
            isAutoGenerated: true,
            prompts: ['prompt1']
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should not warn when auto-generated skill has mixed components', () => {
      const context = createTestContext({
        skills: new Map([
          ['mixed_skill', {
            name: 'mixed_skill',
            isAutoGenerated: true,
            tools: ['tool1'],
            resources: ['file://1'],
            prompts: []
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });
  });

  describe('Manual Skills', () => {
    it('should not warn about manual skill with no components', () => {
      const context = createTestContext({
        skills: new Map([
          ['manual_skill', {
            name: 'manual_skill',
            description: 'Manual content',
            isAutoGenerated: false,
            skill: 'string' // Manual content via skill field
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should not warn about manual skill with empty components', () => {
      const context = createTestContext({
        skills: new Map([
          ['manual_skill', {
            name: 'manual_skill',
            isAutoGenerated: false,
            tools: [],
            resources: []
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should not warn about skill with no isAutoGenerated field (defaults to false)', () => {
      const context = createTestContext({
        skills: new Map([
          ['default_skill', {
            name: 'default_skill',
            description: 'Default behavior'
            // isAutoGenerated not set - defaults to false
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });
  });

  describe('Multiple Skills', () => {
    it('should detect multiple empty auto-generated skills', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty1', {
            name: 'empty1',
            isAutoGenerated: true
          } as ParsedSkill],
          ['empty2', {
            name: 'empty2',
            isAutoGenerated: true,
            tools: []
          } as ParsedSkill],
          ['valid', {
            name: 'valid',
            isAutoGenerated: true,
            tools: ['tool1']
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(2);
      expect(warnings.find(w => w.message.includes('empty1'))).toBeDefined();
      expect(warnings.find(w => w.message.includes('empty2'))).toBeDefined();
      expect(warnings.find(w => w.message.includes('valid'))).toBeUndefined();
    });

    it('should warn only about auto-generated empty skills, not manual ones', () => {
      const context = createTestContext({
        skills: new Map([
          ['auto_empty', {
            name: 'auto_empty',
            isAutoGenerated: true
          } as ParsedSkill],
          ['manual_empty', {
            name: 'manual_empty',
            isAutoGenerated: false
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].message).toContain('auto_empty');
      expect(warnings[0].message).not.toContain('manual_empty');
    });
  });

  describe('Configuration', () => {
    it('should respect "off" config', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            isAutoGenerated: true
          } as ParsedSkill]
        ]),
        config: {
          enabled: true,
          rules: {
            emptySkills: 'off'
          }
        }
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should use "error" severity when configured', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            isAutoGenerated: true
          } as ParsedSkill]
        ]),
        config: {
          enabled: true,
          rules: {
            emptySkills: 'error'
          }
        }
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].severity).toBe('error');
    });

    it('should use "warning" severity when configured as "warn"', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            isAutoGenerated: true
          } as ParsedSkill]
        ]),
        config: {
          enabled: true,
          rules: {
            emptySkills: 'warn'
          }
        }
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].severity).toBe('warning');
    });
  });

  describe('Edge Cases', () => {
    it('should handle empty context', () => {
      const context = createTestContext();
      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });

    it('should handle skill with no components field at all', () => {
      const context = createTestContext({
        skills: new Map([
          ['no_components', {
            name: 'no_components',
            isAutoGenerated: true,
            description: 'No components field'
            // No components field
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      expect(warnings[0].message).toContain('no_components');
    });

    it('should handle skill with only one component type having items', () => {
      const context = createTestContext({
        skills: new Map([
          ['partial_skill', {
            name: 'partial_skill',
            isAutoGenerated: true,
            tools: [],
            resources: ['file://1'], // Only this has content
            prompts: []
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      // Should not warn - has at least one component
      expect(warnings).toHaveLength(0);
    });

    it('should handle skill with single component', () => {
      const context = createTestContext({
        skills: new Map([
          ['single_skill', {
            name: 'single_skill',
            isAutoGenerated: true,
            tools: ['single_tool']
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(0);
    });
  });

  describe('Suggestion Content', () => {
    it('should provide actionable suggestions', () => {
      const context = createTestContext({
        skills: new Map([
          ['empty_skill', {
            name: 'empty_skill',
            isAutoGenerated: true
          } as ParsedSkill]
        ])
      });

      const warnings = checkEmptySkills(context);

      expect(warnings).toHaveLength(1);
      const suggestion = warnings[0].suggestion || '';
      expect(suggestion).toContain('Add component arrays');
      expect(suggestion).toContain('tools');
      expect(suggestion).toContain('resources');
      expect(suggestion).toContain('Switch to manual content');
      expect(suggestion).toContain('skill');
    });
  });
});
