/**
 * Empty Skills Rule
 *
 * Detects skills that use `components` field but have no actual components
 * (empty arrays or no components). This is typically a mistake.
 */

import type { ValidationContext, ValidationWarning } from '../types.js';

/**
 * Check for skills with empty components
 * Time complexity: O(S) where S = skills
 */
export function checkEmptySkills(
  context: ValidationContext
): ValidationWarning[] {
  const warnings: ValidationWarning[] = [];

  if (context.config.rules?.emptySkills === 'off') {
    return warnings;
  }

  const severity = context.config.rules?.emptySkills === 'error' ? 'error' : 'warning';

  for (const [skillName, skill] of context.skills) {
    // Only check auto-generated skills
    if (!skill.isAutoGenerated) continue;

    const hasComponents =
      (skill.tools && skill.tools.length > 0) ||
      (skill.resources && skill.resources.length > 0) ||
      (skill.prompts && skill.prompts.length > 0);

    if (!hasComponents) {
      warnings.push({
        rule: 'empty-skill-components',
        severity,
        message: `Skill '${skillName}' uses auto-generation but has no components. Auto-generated skills need at least one component to generate content from.`,
        suggestion:
          `1. Add component arrays: tools: ['tool1'], resources: ['resource1']\n` +
          `2. Switch to manual content using skill field`
      });
    }
  }

  return warnings;
}
