/**
 * Invalid Component References Rule
 *
 * Detects skills that reference non-existent tools, resources, or prompts
 * in their `components` field. This is a correctness issue.
 */

import type { ValidationContext, ValidationWarning } from '../types.js';

/**
 * Check for skills referencing non-existent components
 * Time complexity: O(S × C) where S = skills, C = avg components per skill
 */
export function checkInvalidReferences(
  context: ValidationContext
): ValidationWarning[] {
  const warnings: ValidationWarning[] = [];

  if (context.config.rules?.invalidReferences === 'off') {
    return warnings;
  }

  const severity = context.config.rules?.invalidReferences === 'error' ? 'error' : 'warning';

  for (const [skillName, skill] of context.skills) {
    // Only check auto-generated skills
    if (!skill.isAutoGenerated) continue;

    // Check tools
    if (skill.tools) {
      for (const toolName of skill.tools) {
        if (!context.tools.has(toolName)) {
          const availableTools = Array.from(context.tools.keys());
          warnings.push({
            rule: 'invalid-tool-reference',
            severity,
            message: `Skill '${skillName}' references tool '${toolName}' which doesn't exist.`,
            suggestion: availableTools.length > 0
              ? `Available tools: ${availableTools.join(', ')}`
              : 'No tools are defined in this server.',
            relatedItems: availableTools
          });
        }
      }
    }

    // Check resources
    if (skill.resources) {
      for (const uri of skill.resources) {
        if (!context.resources.has(uri)) {
          const availableResources = Array.from(context.resources.keys());
          warnings.push({
            rule: 'invalid-resource-reference',
            severity,
            message: `Skill '${skillName}' references resource '${uri}' which doesn't exist.`,
            suggestion: availableResources.length > 0
              ? `Available resources: ${availableResources.join(', ')}`
              : 'No resources are defined in this server.',
            relatedItems: availableResources
          });
        }
      }
    }

    // Check prompts
    if (skill.prompts) {
      for (const promptName of skill.prompts) {
        if (!context.prompts.has(promptName)) {
          const availablePrompts = Array.from(context.prompts.keys());
          warnings.push({
            rule: 'invalid-prompt-reference',
            severity,
            message: `Skill '${skillName}' references prompt '${promptName}' which doesn't exist.`,
            suggestion: availablePrompts.length > 0
              ? `Available prompts: ${availablePrompts.join(', ')}`
              : 'No prompts are defined in this server.',
            relatedItems: availablePrompts
          });
        }
      }
    }
  }

  return warnings;
}
