/**
 * Non-Hidden Components Rule
 *
 * Detects skills that reference components that are NOT hidden. This is
 * typically a design smell - skills are meant for progressive disclosure
 * of hidden capabilities.
 */

import type { ValidationContext, ValidationWarning } from '../types.js';

/**
 * Check for skills referencing non-hidden components
 * Time complexity: O(S × C) where S = skills, C = avg components per skill
 */
export function checkNonHiddenComponents(
  context: ValidationContext
): ValidationWarning[] {
  const warnings: ValidationWarning[] = [];

  if (context.config.rules?.nonHiddenComponents === 'off') {
    return warnings;
  }

  const severity = context.config.rules?.nonHiddenComponents === 'error' ? 'error' : 'warning';

  for (const [skillName, skill] of context.skills) {
    // Only check auto-generated skills
    if (!skill.isAutoGenerated) continue;

    // Check tools
    if (skill.tools) {
      for (const toolName of skill.tools) {
        const tool = context.tools.get(toolName);
        if (tool && !tool.hidden) {
          warnings.push({
            rule: 'non-hidden-component',
            severity,
            message: `Skill '${skillName}' references tool '${toolName}' which is not hidden. Skills should typically reference hidden items for progressive disclosure.`,
            suggestion:
              `1. Mark the tool as hidden if it should be progressive\n` +
              `2. Remove the tool from skill component arrays if it should be public\n` +
              `3. Disable this warning if mixing public/hidden is intentional`
          });
        }
      }
    }

    // Check resources
    if (skill.resources) {
      for (const uri of skill.resources) {
        const resource = context.resources.get(uri);
        if (resource && !resource.hidden) {
          warnings.push({
            rule: 'non-hidden-component',
            severity,
            message: `Skill '${skillName}' references resource '${uri}' which is not hidden. Skills should typically reference hidden items for progressive disclosure.`,
            suggestion: `Mark as hidden or remove from skill component arrays`
          });
        }
      }
    }

    // Check prompts
    if (skill.prompts) {
      for (const promptName of skill.prompts) {
        const prompt = context.prompts.get(promptName);
        if (prompt && !prompt.hidden) {
          warnings.push({
            rule: 'non-hidden-component',
            severity,
            message: `Skill '${skillName}' references prompt '${promptName}' which is not hidden. Skills should typically reference hidden items for progressive disclosure.`,
            suggestion: `Mark as hidden or remove from skill component arrays`
          });
        }
      }
    }
  }

  return warnings;
}
